/**
 * WASM Loader — initializes the EZ-Claw WASM module.
 *
 * Loads the wasm-pack generated module and provides typed wrappers
 * for all WASM exports. This is the single entry point for all
 * WASM interactions from TypeScript.
 */

// Type declarations for the WASM module (generated by wasm-pack)
interface EzClawWasm {
    // Core
    version(): string;
    health_check(): boolean;

    // Config
    WasmConfig: {
        new(): WasmConfigInstance;
        from_toml(toml: string): WasmConfigInstance;
        from_json(json: string): WasmConfigInstance;
    };

    // Agent
    WasmAgent: {
        new(config_json: string): WasmAgentInstance;
    };

    // Providers
    build_provider_request(
        messages_json: string,
        model: string,
        temperature: number,
        stream: boolean
    ): string;
    parse_sse_line(line: string): string;
    provider_base_url(provider: string): string;

    // Memory
    memory_create_table_sql(): string;
    memory_store_sql(
        id: string,
        key: string,
        content: string,
        category: string,
        timestamp: string,
        session_id: string
    ): string;
    memory_recall_sql(query: string, limit: number, session_id: string): string;
    memory_get_sql(key: string): string;
    memory_list_sql(category: string, session_id: string): string;
    memory_forget_sql(key: string): string;
    memory_count_sql(): string;
    compute_tfidf_score(query: string, document: string): number;
    wasm_cosine_similarity(a: Float32Array, b: Float32Array): number;
    wasm_hybrid_merge(
        vector_results_json: string,
        keyword_results_json: string,
        vector_weight: number,
        keyword_weight: number,
        limit: number
    ): string;

    // Identity
    parse_aieos_identity(json_str: string): string;
    default_aieos_identity(agent_name: string, user_name: string): string;
    is_aieos_format(format: string): boolean;

    // Crypto
    encrypt(plaintext: string, passphrase: string): string;
    decrypt(hex_data: string, passphrase: string): string;

    // Text
    wasm_estimate_tokens(text: string): number;
    strip_markdown(text: string): string;
    truncate_to_tokens(text: string, max_tokens: number): string;
}

interface WasmConfigInstance {
    to_toml(): string;
    to_json(): string;
    api_key: string | undefined;
    default_provider: string | undefined;
    default_model: string | undefined;
    default_temperature: number;
    api_url: string | undefined;
    max_tool_iterations: number;
    max_history_messages: number;
    memory_backend: string;
    memory_auto_save: boolean;
    identity_format: string;
    encrypt_secrets: boolean;
    free(): void;
}

interface WasmAgentInstance {
    update_config(config_json: string): void;
    build_messages(
        history_json: string,
        memories_json: string,
        identity_content: string,
        datetime_str: string
    ): string;
    parse_tool_calls(response_json: string): string;
    format_tool_result(
        tool_call_id: string,
        tool_name: string,
        result: string
    ): string;
    estimate_context_tokens(messages_json: string): number;
    free(): void;
}

// Singleton WASM instance
let wasmInstance: EzClawWasm | null = null;

/**
 * Initialize the WASM module.
 * Must be called before any other WASM functions.
 */
export async function initWasm(): Promise<EzClawWasm> {
    if (wasmInstance) return wasmInstance;

    try {
        // Dynamic import of the wasm-pack generated module
        const wasm = await import('@wasm/ezclaw_core.js');
        await wasm.default();
        wasmInstance = wasm as unknown as EzClawWasm;
        console.log(`[EZ-Claw] WASM loaded: ${wasmInstance.version()}`);
        return wasmInstance;
    } catch (err) {
        console.error('[EZ-Claw] Failed to load WASM module:', err);
        throw err;
    }
}

/**
 * Get the initialized WASM instance (throws if not initialized).
 */
export function getWasm(): EzClawWasm {
    if (!wasmInstance) {
        throw new Error('WASM not initialized. Call initWasm() first.');
    }
    return wasmInstance;
}

/**
 * Check if WASM is loaded and operational.
 */
export function isWasmReady(): boolean {
    return wasmInstance !== null && wasmInstance.health_check();
}

// Re-export types for TypeScript consumers
export type { EzClawWasm, WasmConfigInstance, WasmAgentInstance };
