/// <reference types="svelte" />
/// <reference types="vite/client" />

// WASM module declarations (generated by wasm-pack at build time into pkg/)
declare module '@wasm/ezclaw_core.js' {
    export default function init(): Promise<void>;
    export function version(): string;
    export function health_check(): boolean;
    export function build_provider_request(messages: string, model: string, temp: number, stream: boolean): string;
    export function parse_sse_line(line: string): string;
    export function provider_base_url(provider: string): string;
    export function memory_create_table_sql(): string;
    export function compute_tfidf_score(query: string, document: string): number;
    export function wasm_cosine_similarity(a: Float32Array, b: Float32Array): number;
    export function wasm_hybrid_merge(vr: string, kr: string, vw: number, kw: number, limit: number): string;
    export function parse_aieos_identity(json: string): string;
    export function default_aieos_identity(agent: string, user: string): string;
    export function is_aieos_format(format: string): boolean;
    export function encrypt(plaintext: string, passphrase: string): string;
    export function decrypt(hex_data: string, passphrase: string): string;
    export function wasm_estimate_tokens(text: string): number;
    export function strip_markdown(text: string): string;
    export function truncate_to_tokens(text: string, max_tokens: number): string;
    export class WasmConfig {
        constructor();
        static from_toml(toml: string): WasmConfig;
        static from_json(json: string): WasmConfig;
        to_toml(): string;
        to_json(): string;
        free(): void;
    }
    export class WasmAgent {
        constructor(config_json: string);
        update_config(config_json: string): void;
        build_messages(history: string, memories: string, identity: string, dt: string): string;
        parse_tool_calls(response: string): string;
        format_tool_result(id: string, name: string, result: string): string;
        estimate_context_tokens(messages: string): number;
        free(): void;
    }
}
